[project]
name = "week-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "polars>=1.33.0",
    "quarto>=0.1.0",
    "seaborn>=0.13.2",
]
